// <auto-generated />
using System;
using FGO_CE_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FGO_CE_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230904204658_Changes")]
    partial class Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CollectionNo")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "collectionNo");

                    b.Property<int>("ExtraAssetsID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Guid");

                    b.HasIndex("ExtraAssetsID");

                    b.ToTable("CE");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE_ExtraAssets", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CharaGraphID")
                        .HasColumnType("int");

                    b.Property<int>("FacesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CharaGraphID");

                    b.HasIndex("FacesID");

                    b.ToTable("ExtraAssets");

                    b.HasAnnotation("Relational:JsonPropertyName", "extraAssets");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE_Skill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid?>("CEGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CEGuid");

                    b.ToTable("Skill");

                    b.HasAnnotation("Relational:JsonPropertyName", "skills");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.ExtraAssets_CharaGraph", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CharaGraph");

                    b.HasAnnotation("Relational:JsonPropertyName", "charaGraph");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.ExtraAssets_Faces", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Faces");

                    b.HasAnnotation("Relational:JsonPropertyName", "faces");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.Functions_Sval", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("EventID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "EventId");

                    b.Property<int>("FunctionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FunctionID");

                    b.ToTable("Sval");

                    b.HasAnnotation("Relational:JsonPropertyName", "svals");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.Skills_Function", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SkillID");

                    b.ToTable("Function");

                    b.HasAnnotation("Relational:JsonPropertyName", "functions");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.EventModels.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EventID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("ID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE", b =>
                {
                    b.HasOne("FGO_CE_Manager.Data.CEModels.CE_ExtraAssets", "ExtraAssets")
                        .WithMany()
                        .HasForeignKey("ExtraAssetsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraAssets");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE_ExtraAssets", b =>
                {
                    b.HasOne("FGO_CE_Manager.Data.CEModels.ExtraAssets_CharaGraph", "CharaGraph")
                        .WithMany()
                        .HasForeignKey("CharaGraphID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGO_CE_Manager.Data.CEModels.ExtraAssets_Faces", "Faces")
                        .WithMany()
                        .HasForeignKey("FacesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharaGraph");

                    b.Navigation("Faces");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE_Skill", b =>
                {
                    b.HasOne("FGO_CE_Manager.Data.CEModels.CE", null)
                        .WithMany("Skills")
                        .HasForeignKey("CEGuid");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.Functions_Sval", b =>
                {
                    b.HasOne("FGO_CE_Manager.Data.CEModels.Skills_Function", "Function")
                        .WithMany("Svals")
                        .HasForeignKey("FunctionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.Skills_Function", b =>
                {
                    b.HasOne("FGO_CE_Manager.Data.CEModels.CE_Skill", "Skill")
                        .WithMany("Functions")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.CE_Skill", b =>
                {
                    b.Navigation("Functions");
                });

            modelBuilder.Entity("FGO_CE_Manager.Data.CEModels.Skills_Function", b =>
                {
                    b.Navigation("Svals");
                });
#pragma warning restore 612, 618
        }
    }
}
